### ISSUE TITLE
Add support for flashing without starting the node afterwards

### ISSUE THREAD

**Issue by thepapanoob** [turing-machines/tpi#14]
Hello everyone,

it would be great if there would be an option to flash the nodes without powering it on afterwards so you can provide configuration files to the boot partition without having to uncleanly shutting the node down beforehand.

Sincerely,
ThePapanoob

**Comment by svenrademakers** [comment]
It depends a bit on what your use case is and what will be desirable. I agree with you that leaving it off is less of an annoyance than turning it on.
Alternatively, i was thinking of returning to the power state before you started the flash operation. So if you execute a flash command when the node is off, it will stay off and vice versa.

**Comment by svenrademakers** [comment]
fixed in https://github.com/turing-machines/bmcd/pull/72
