### ISSUE TITLE
arch package fails to build without updated depemdencies

### ISSUE THREAD

**Issue by dlasky** [turing-machines/tpi#29]
builds fine off main when run locally. seems like we just need a release bump

**Comment by svenrademakers** [comment]
bumped the tpi package v1.0.6 to AUR, thanks for reporting

**Comment by dlasky** [comment]
Hrm annoyingly that didnt do it

Someone left this excellent comment on the aur package however:

> nogweii [1] added the following comment to tpi [2]:

> Could you add `options=('!lto')` to the PKGBUILD? Disabling LTO makes
compiling work on x86-64 platforms (otherwise you get a bunch of
linker errors).

> There is a bunch of [discussion among the pacman devs on how to solve
this](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/131),
but that isn't going quickly. (Nor should it! It's complicated.)
